---
kind: WriteFile
version: v1
metadata:
  name: s3-example-bucket-cfn-template
  executeOnlyOnceOnApply: true
spec:
  targetFile: /tmp/cloudformation_templates/cfn-example.yaml
  data: |
    ---
    AWSTemplateFormatVersion: "2010-09-09"
    Description: 'An example S3 bucket template'
    Parameters:
      BucketNameParameter:
        Type: String
    Resources:
      S3ExampleBucket:
        Type: 'AWS::S3::Bucket'
        DeletionPolicy: Retain
        Properties:
          BucketName: !Ref BucketNameParameter
    Outputs:
      ExampleS3Bucket:
        Description: 'Example S3 Bucket Name'
        Value: !Ref S3ExampleBucket
        Export:
          Name: !Join [ ":", [ !Ref "AWS::StackName", !Ref S3ExampleBucket ] ]
---
kind: ShellScript
version: v1
metadata:
  name: random-s3-bucket-name
  skipDeleteAll: true
spec:
  shellInterpreter: bash
  source:
    type: inLine
    value: |
      chars=abcdefghijklmnopqrstuvwxyz-1234567890
      for i in {1..16} ; do
      echo -n "${chars:RANDOM%${#chars}:1}"
      done
      echo
---
kind: AwsBoto3Session
version: v1
metadata:
  name: aws-boto3-session
  skipApplyAll: true
  skipDeleteAll: true
spec:
  awsRegion: eu-central-1
  profileName: my-profile
---
kind: AwsBoto3S3Bucket
version: v1
metadata:
  name: animus-artifacts-for-cloudformation
  dependencies:
    apply:
    -  aws-boto3-session
    delete:
    -  aws-boto3-session
  executeOnlyOnceOnApply: true
spec:
  awsBoto3Session:  aws-boto3-session
  name: animus-artifacts-for-cloudformation
---
kind: AwsBoto3S3Files
version: v1
metadata:
  name: cfn-upload-to-s3
  dependencies:
    apply:
    - aws-boto3-session
    - animus-artifacts-for-cloudformation
    delete:
    - aws-boto3-session
    - animus-artifacts-for-cloudformation
spec:
  awsBoto3Session: aws-boto3-session
  s3Bucket: '{{ .Variables.AwsBoto3S3Bucket:animus-artifacts-for-cloudformation:default:NAME }}'
  globalOverwrite: true
  destinationDirectory: /default
  transferLogFile: /tmp/log/file_transfer.log
  sources:
  - sourceType: localDirectories
    recurse: true
    baseDirectory: /tmp
    verifyChecksums: false
    directories:
    - cloudformation_templates
  ifFileExists:
    overWrite: true
  onError: warn
  actionExtraFilesOnS3: keep
---
kind: AwsBoto3CloudFormationTemplateParameters
version: v1
metadata:
  name: aws-s3-example-bucket-cfn-template-deployment-parameters
  executeOnlyOnceOnApply: true
  skipApplyAll: true
  skipDeleteAll: true
spec:
  parameters:
  - parameterName: 'BucketNameParameter'
    parameterValue: '{{ .Variables.ShellScript:random-s3-bucket-name:default:STDOUT }}'
---
kind: AwsBoto3CloudFormationTemplateTags
version: v1
metadata:
  name: aws-s3-example-bucket-cfn-template-deployment-tags
  executeOnlyOnceOnApply: true
  skipApplyAll: true
  skipDeleteAll: true
spec:
  tags:
  - tagName: 'Comment'
    tagValue: 'Demonstrating Animus Deployment'
---
kind: AwsBoto3CloudFormationTemplate
version: v1
metadata:
  name: aws-s3-example-bucket-cfn-template-deployment
  dependencies:
    apply:
    - s3-example-bucket-cfn-template
    - random-s3-bucket-name
    - aws-s3-example-bucket-cfn-template-deployment-parameters
    - aws-s3-example-bucket-cfn-template-deployment-tags
    - aws-boto3-session
    - cfn-upload-to-s3
  executeOnlyOnceOnApply: true
  skipDeleteAll: true
spec:
  awsBoto3SessionReference: aws-boto3-session
  templateURL:
    s3BucketReference: animus-artifacts-for-cloudformation
    pathToTemplate: /default/cfn-example.yaml
  templatePath: '{{ .Variables.WriteFile:s3-example-bucket-cfn-template:default:FILE_PATH }}'
  parameterReferences:
  - aws-s3-example-bucket-cfn-template-deployment-parameters
  tagReferences:
  - aws-s3-example-bucket-cfn-template-deployment-tags